name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:

  docker-1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build application
        run: |
          echo "Build application here pranav"
          echo "AWS secret is configured"
          docker version
          # mvn clean package

  docker-2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build application
        run: |
          echo "Build application here pranav 2222222222"

      - name: Build application
        run: |
          echo "Build application here pranav 2222222222"
